### ISSUE TITLE
Move away the documentation from the Wiki

### ISSUE THREAD

**Issue by dalf** [searx/searx#1785]
To do after https://github.com/asciimoo/searx/pull/1776 is merged : see https://github.com/asciimoo/searx/pull/1776#issuecomment-568264083

Most of the wiki content should be moved away to the reST documentation:
- [x] settings.yml : https://github.com/asciimoo/searx/wiki/settings.yml : description of the general settings to move away & update.
- [x] docker: https://github.com/asciimoo/searx/wiki/Docker-developement-environment : to merge/remove most probably (could be use https://github.com/searx/searx-docker )
- [x] engines: https://github.com/asciimoo/searx/wiki/existing-engines : to remove, since it is generate automatically with the PR #1776   see [engines](https://asciimoo.github.io/searx/admin/engines.html)

About the reverse proxy configuration / installation:
- [x] https://github.com/asciimoo/searx/wiki/How-to-create-and-configure-SSL : https://ssl-config.mozilla.org/ will provide better up to date configuration BUT it should include the HTTP headers (another way to deal with HTTP headers : https://github.com/asciimoo/searx/issues/715 )
- [ ] https://github.com/asciimoo/searx/wiki/Searx-with-haproxy : same as the previous link.
- [x] https://github.com/asciimoo/searx/wiki/Web-server-hardening-(Apache) : to remove (?) see below.
- [x] https://github.com/asciimoo/searx/wiki/Installation-on-RHEL-7---CentOS-7 : it seems only the "yum install" part is different (use tabbed views from https://github.com/return42/searx/commit/92afe68d6532c and provide installation instructions with one tab per distrubution)
- [x] https://github.com/asciimoo/searx/wiki/Installation : to remove.

A way to deal with the reverse proxy configurations (if possible):
* define some variables (from [this](https://github.com/searx/searx-docker/blob/f2e6ca4a610d9ccf66d4e16ac210bdb1bd4fff0c/Caddyfile#L19) or somewhere else)
* generate the Apache, nginx, caddy, haproxy configurations using some templates, useful especially for the HTTP headers (Content-Security-Policy header etc...). 

It would avoid different versions of the configuration.

Perhaps, each reverse proxy should have it's own page in the reST documentation.

**Comment by return42** [comment]
> idea: in the doc, provide installation instructions with one tab per distrubution

I have seen such a "one tab per distrubution" sphinx-theme (or directive?) .. can't remember what and where .. do you have a link, pointing in the right direction / thanks!

**Comment by dalf** [comment]
I'm not used to sphinx.

I found this:
* https://sphinxcontrib-contentui.readthedocs.io/en/latest/tabs.html : column tabs, column content, toggle headers could be useful.
* https://github.com/djungelorm/sphinx-tabs : only tabs
* specific to MongoDB: https://docs.mongodb.com/meta/tutorials/tabbed-content/

All require JS.

Note: the searx simple theme uses pure CSS tab
* https://github.com/asciimoo/searx/blob/master/searx/static/themes/simple/less/toolkit.less#L215
* https://github.com/asciimoo/searx/blob/master/searx/templates/simple/macros.html#L53
* something similar : https://codepen.io/renatorib/pen/rlpfj

**Comment by return42** [comment]
> I'm not used to sphinx.

Ups, sorry I thought you fire your preferences from the hip.  Was not my aim to instruct you to do a research.   Anyway, you brought up what is needed.

> All require JS.

Pure CSS has its charm , but it is also hard to maintain or extend.  Since JS is already needed by Sphinx (search index), I do not have problems using JS .. I have seen very rare pure CSS Sphinx themes.

> column tabs, column content, toggle headers could be useful.

From the JS solutions I chose [sphinx-tabs](https://github.com/djungelorm/sphinx-tabs). From my personal view: it follows more the (old) unix philosophy [do one thing and do it  this well](https://en.wikipedia.org/wiki/Unix_philosophy#Do_One_Thing_and_Do_It_Well). sphinx-tabs includes [Sphinx UI](https://semantic-ui.com/), on the other side, sphinxcontrib-contentui is more handmade and needs less resources. Both have pros and cons .. at least, sphinx-tabs are group able, which seems to fits more to our needs. 

Here is a link shows the usage of tabbed views (don't bookmark): https://return42.github.io/searx/dev/reST.html#tabbed-views

**Comment by return42** [comment]
FYI: I add the Searx-instances wiki to the docs https://github.com/asciimoo/searx/pull/1791 :

- [x] Public instances: https://github.com/asciimoo/searx/wiki/Searx-instances Public instances wiki was vandalized so many times, see https://github.com/asciimoo/searx/issues/1770#issuecomment-570776655

Udate: job done, see https://asciimoo.github.io/searx/user/public_instances.html

**Comment by unixfox** [comment]
> > For the whole documentation for both case.
> 
> Do we really need "github" corners? .. we have "Project Links" on top of the left navigation bar and the link to the "Source" is the topmost .. compare: [asciimoo.github.io/searx](https://asciimoo.github.io/searx/)

Not everyone is used to GitHub, if there is a button that leads to the ability to directly add content to the page it's way easier than going to the source code then finding where the file of the page is (because currently it's explained nowhere how to edit the documentation) and finally edit the file.

One thing that creeped me a bit when moving the wiki to the documentation is the ease of editing pages, I don't want to see an amount of contributors reduced because we moved to a reST documentation. The wiki was really easy to edit, the documentation should follow the same simplicity.

**Comment by return42** [comment]
> One thing that creeped me a bit when moving the wiki to the documentation is the ease of editing pages, I don't want to see an amount of contributors reduced because we moved to a reST documentation.

I can understand, that is an argument. On the other side I am not a real fan of to much tooling other than a simple git command line.  I also see some drawbacks: Our contributors need a github account, this will lock out other good programmers who do not want to have a github account / most CI quality tooling needs to commit first your mistakes ... 

I personally prefer less bindings as possible. but this is not my decision, it is the decision of the maintainer .. so I play the ball to @asciimoo ...

**Comment by asciimoo** [comment]
>  Our contributors need a github account, this will lock out other good programmers who do not want to have a github account / most CI quality tooling needs to commit first your mistakes ...

I accept patches in email.

> I personally prefer less bindings as possible. but this is not my decision, it is the decision of the maintainer .. so I play the ball to @asciimoo ...

I agree

**Comment by return42** [comment]
I just want to leave a remark here, that we have to update the https://asciimoo.github.io/searx/user/public_instances.html page to the new searx-stats2 workflow, see https://github.com/dalf/searx-stats2/issues/7#issuecomment-585720862

Update: done #1843
