### ISSUE TITLE
Merge conflict, pip and python problem during upgrade 0.15.0 to 0.17.0

### ISSUE THREAD

**Issue by r4dh4l** [searx/searx#2138]
Hi,

following https://searx.github.io/searx/admin/update-searx.html I tried to upgrade my searx setup from 0.15.0 to 0.17.0 which was installed with the [step by step](https://searx.github.io/searx/admin/installation-searx.html) guide. I tried the following commands and got the following warnings/errors:

```
su - searx -s /bin/bash
cp searx/settings.yml searx/settings_bkp2020-08-09.yml
git stash
git pull origin master
$ git stash apply
Auto-merging searx/settings.yml
CONFLICT (content): Merge conflict in searx/settings.yml

$ ./manage.sh update_packages
./manage.sh: 22: ./manage.sh: pip: not found
```

1. Is there a way to tell the upgrade process to just overwrite the `searx/settings.yml` (because I would configure it again after upgrading)?

2. Why pip is needed at the end? I can not remember that pip was needed during the initial setup.

Thx for searx!

Edit: The history of errors in this report (and solution, if available):

- [X] `pip: not found`: https://github.com/searx/searx/issues/2138#issuecomment-672496124 (forgot to switch into virtual environment)
- [ ] `Merge conflict in searx/settings.yml`: https://github.com/searx/searx/issues/2138#issuecomment-672496124 (workaround: skip `git stash apply`)
- [X] `Internal Server Error`/`no python application found`: https://github.com/searx/searx/issues/2138#issuecomment-678712306 (forgot to create a python3 environment: https://github.com/searx/searx/issues/2138#issuecomment-695121488)
- [X] `Python2 is no longer supported`: https://github.com/searx/searx/issues/2138#issuecomment-695121488 (forgot to adjust `/etc/uwsgi/apps-available/searx.ini` to new environment: https://github.com/searx/searx/issues/2138#issuecomment-695349247)
- [ ] `ImportError: No module named site`: https://github.com/searx/searx/issues/2138#issuecomment-695367334

**Comment by MarcAbonce** [comment]
Pip is needed to install/upgrade dependencies. In your example I think you're not inside your virtual environment and that's why pip is not found. If that's the case, then you can usually start it with `./env/bin/activate` but it depends on the name you gave your virtual environment when you first installed it (there should be an `env` or `searx-ve` or `searx-pyenv` or some similarly named directory under the project's root). When your virtual environment is activated you should see it's name right before the shell prompt like `(env) $` and then you can run all the other commands.

If you want to overwrite your settings, just skip the `git stash apply` step and your settings will not appear, but then your searx instance will have all the default values.

**Comment by r4dh4l** [comment]
> Pip is needed to install/upgrade dependencies. In your example I think you're not inside your virtual environment and that's why pip is not found. If that's the case, then you can usually start it with ./env/bin/activate but it depends on the name you gave your virtual environment when you first installed it (there should be an env or searx-ve or searx-pyenv or some similarly named directory under the project's root). When your virtual environment is activated you should see it's name right before the shell prompt like (env) $ and then you can run all the other commands.

Thank you so much, that did the trick. Searx was such a "fire and forget" setup, that I totally forgot this aspect.

> If you want to overwrite your settings, just skip the git stash apply step and your settings will not appear, but then your searx instance will have all the default values.

The point I don't understand: I tried to `mv` the file `searx/settings.yml` to another before I applied `git stash apply` and still got `Merge conflict in searx/settings.yml`. Why is this the case?
I would like to keep my current `searx/settings.yml` and settings from a newer version of `settings.yml` later.

**Comment by r4dh4l** [comment]
I tried again and recognized I forgot to create a new python env with python3 (`python3 -m venv /usr/local/searx/searx-env`). Now the uipgrade process works without the error `no python application found ` starting uwsgi.service at the end. Unfortunately the Searx webinterface didn't appear. `/var/log/uwsgi/app/searx.log` lists:

```
Sat Sep 19 00:56:43 2020 - DAMN ! worker 1 (pid: 9014) died :( trying respawn ...
Sat Sep 19 00:56:43 2020 - Respawned uWSGI worker 1 (new pid: 9015)
 Python2 is no longer supported
```

Any ideas?

**Comment by 0xhtml** [comment]
Could you post the contents of `/etc/uwsgi/apps-available/searx.ini`? It seems like uwsgi uses Python 2 instead of 3.

**Comment by r4dh4l** [comment]
Thx for your help @dalf 

```
[uwsgi]
# Who will run the code
uid = searx
gid = searx

# disable logging for privacy
disable-logging = true

# Number of workers (usually CPU count)
#workers = 4
workers = 1

# The right granted on the created socket
chmod-socket = 666

# Plugin to use and interpretor config
single-interpreter = true
master = true
plugin = python
lazy-apps = true
enable-threads = true

# Module to import
module = searx.webapp

# Virtualenv and python path
virtualenv = /usr/local/searx/searx-ve/
pythonpath = /usr/local/searx/
chdir = /usr/local/searx/searx/

# filtron
http = 127.0.0.1:8888
```

I noticed that I forgot to adjust `/usr/local/searx/searx-ve/` to the new environment for python3, in my case `/usr/local/searx/searx-py3env/`.

However: After adjusting the path I get an new error after restarting uwsgi by `journalctl`:

```
Sep 19 21:43:24 f941d33e0d-p-vm-searx-15ee6757c9 avahi-daemon[673]: Host name conflict, retrying with f941d33e0d-p-vm-searx-15ee6757c9-297
Sep 19 21:43:24 f941d33e0d-p-vm-searx-15ee6757c9 avahi-daemon[673]: Registering new address record for fdb8:4dea:e5eb::3fe on ens18.*.
Sep 19 21:43:24 f941d33e0d-p-vm-searx-15ee6757c9 avahi-daemon[673]: Registering new address record for fdb8:4dea:e5eb:0:fca2:cfff:fe71:4028 on ens18.*.
Sep 19 21:43:24 f941d33e0d-p-vm-searx-15ee6757c9 avahi-daemon[673]: Registering new address record for fdb8:4dea:e5eb:0:25db:d61a:a141:755b on ens18.*.
Sep 19 21:43:24 f941d33e0d-p-vm-searx-15ee6757c9 avahi-daemon[673]: Registering new address record for 192.168.1.134 on ens18.IPv4.
Sep 19 21:43:31 f941d33e0d-p-vm-searx-15ee6757c9 systemd[1]: Starting LSB: Start/stop uWSGI server instance(s)...
-- Subject: Unit uwsgi.service has begun start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit uwsgi.service has begun starting up.
Sep 19 21:43:31 f941d33e0d-p-vm-searx-15ee6757c9 uwsgi[4533]: Starting app server(s): uwsgi -> ! failed!
Sep 19 21:43:31 f941d33e0d-p-vm-searx-15ee6757c9 systemd[1]: uwsgi.service: Control process exited, code=exited status=1
Sep 19 21:43:31 f941d33e0d-p-vm-searx-15ee6757c9 systemd[1]: Failed to start LSB: Start/stop uWSGI server instance(s).
-- Subject: Unit uwsgi.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit uwsgi.service has failed.
--
-- The result is failed.
Sep 19 21:43:31 f941d33e0d-p-vm-searx-15ee6757c9 systemd[1]: uwsgi.service: Unit entered failed state.
Sep 19 21:43:31 f941d33e0d-p-vm-searx-15ee6757c9 systemd[1]: uwsgi.service: Failed with result 'exit-code'.
Sep 19 21:43:44 f941d33e0d-p-vm-searx-15ee6757c9 avahi-daemon[673]: Withdrawing address record for fdb8:4dea:e5eb:0:fca2:cfff:fe71:4028 on ens18.
Sep 19 21:43:44 f941d33e0d-p-vm-searx-15ee6757c9 avahi-daemon[673]: Withdrawing address record for fdb8:4dea:e5eb:0:25db:d61a:a141:755b on ens18.
```

**Comment by 0xhtml** [comment]
Could you post the output of `systemctl status uwsgi.service`? There is some error starting uwsgi.

**Comment by r4dh4l** [comment]
```
# systemctl status uwsgi.service
● uwsgi.service - LSB: Start/stop uWSGI server instance(s)
   Loaded: loaded (/etc/init.d/uwsgi; generated; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2020-09-19 21:46:37 CEST; 3h 7min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 4323 ExecStop=/etc/init.d/uwsgi stop (code=exited, status=0/SUCCESS)
  Process: 4712 ExecStart=/etc/init.d/uwsgi start (code=exited, status=1/FAILURE)

Sep 19 21:46:36 f941d33e0d-p-vm-searx-15ee6757c9 systemd[1]: Starting LSB: Start/stop uWSGI server instance(s)...
Sep 19 21:46:37 f941d33e0d-p-vm-searx-15ee6757c9 uwsgi[4712]: Starting app server(s): uwsgi -> ! failed!
Sep 19 21:46:37 f941d33e0d-p-vm-searx-15ee6757c9 systemd[1]: uwsgi.service: Control process exited, code=exited status=1
Sep 19 21:46:37 f941d33e0d-p-vm-searx-15ee6757c9 systemd[1]: Failed to start LSB: Start/stop uWSGI server instance(s).
Sep 19 21:46:37 f941d33e0d-p-vm-searx-15ee6757c9 systemd[1]: uwsgi.service: Unit entered failed state.
Sep 19 21:46:37 f941d33e0d-p-vm-searx-15ee6757c9 systemd[1]: uwsgi.service: Failed with result 'exit-code'.
```

**Comment by 0xhtml** [comment]
Ok, could you do as @MarcAbonce said?

> then check if disable-logging is set in /etc/uwsgi/apps-available/searx.ini. If so, then you'll have to temporarily set it to false and restart uwsgi (systemctl restart uwsgi as root user) and try to run searx again.

Temporarily comment out `disable-logging = true` in `/etc/uwsgi/apps-available/searx.ini`, restart uwsgi/searx and post the content of `/var/log/uwsgi/app/searx.log`.
In there should be some error information.

**Comment by r4dh4l** [comment]
Sure, the `/var/log/uwsgi/app/searx.log` since restarting `uwsgi` says:

```
Sun Sep 20 01:33:58 2020 - *** Starting uWSGI 2.0.14-debian (64bit) on [Sun Sep 20 01:33:58 2020] ***
Sun Sep 20 01:33:58 2020 - compiled with version: 6.3.0 20170516 on 30 August 2020 17:14:04
Sun Sep 20 01:33:58 2020 - os: Linux-4.9.0-13-amd64 #1 SMP Debian 4.9.228-1 (2020-07-05)
Sun Sep 20 01:33:58 2020 - nodename: f941d33e0d-p-vm-searx-15ee6757c9
Sun Sep 20 01:33:58 2020 - machine: x86_64
Sun Sep 20 01:33:58 2020 - clock source: unix
Sun Sep 20 01:33:58 2020 - pcre jit disabled
Sun Sep 20 01:33:58 2020 - detected number of CPU cores: 1
Sun Sep 20 01:33:58 2020 - current working directory: /
Sun Sep 20 01:33:58 2020 - writing pidfile to /run/uwsgi/app/searx/pid
Sun Sep 20 01:33:58 2020 - detected binary path: /usr/bin/uwsgi-core
Sun Sep 20 01:33:58 2020 - setgid() to 1003
Sun Sep 20 01:33:58 2020 - setuid() to 1002
Sun Sep 20 01:33:58 2020 - chdir() to /usr/local/searx/searx/
Sun Sep 20 01:33:58 2020 - your processes number limit is 1876
Sun Sep 20 01:33:58 2020 - your memory page size is 4096 bytes
Sun Sep 20 01:33:58 2020 - detected max file descriptor number: 1024
Sun Sep 20 01:33:58 2020 - lock engine: pthread robust mutexes
Sun Sep 20 01:33:58 2020 - thunder lock: disabled (you can enable it with --thunder-lock)
Sun Sep 20 01:33:58 2020 - uWSGI http bound on 127.0.0.1:8888 fd 3
Sun Sep 20 01:33:58 2020 - uwsgi socket 0 bound to UNIX address /run/uwsgi/app/searx/socket fd 7
Sun Sep 20 01:33:58 2020 - Python version: 2.7.13 (default, Aug 22 2020, 10:03:02)  [GCC 6.3.0 20170516]
Sun Sep 20 01:33:58 2020 - Set PythonHome to /usr/local/searx/searx-py3env/
ImportError: No module named site
```

**Comment by 0xhtml** [comment]
Ok, no idea what causes the error `ImportError: No module named site`. Someone else will have to continue from here on. Maybe @MarcAbonce?

**Comment by r4dh4l** [comment]
Thx @0xhtml - just to be clear how I tried to upgrade:

```
$ sudo -i

# systemctl stop uwsgi.service && systemctl status uwsgi.service

(VM snapshot)

# apt update && apt install virtualenv python3-dev python3-babel python3-venv uwsgi uwsgi-plugin-python3 git build-essential libxslt-dev zlib1g-dev libffi-dev libssl-dev shellcheck -y

# su - searx -s /bin/bash

$ cp searx/settings.yml searx/settings.yml_v0150_bkp2020-09-19

$ python3 -m venv /usr/local/searx/searx-py3env

$ . ./searx-py3env/bin/activate

(searx-py3env) git stash
(searx-py3env) git pull origin master
(no "git stash apply" to avoid `CONFLICT (content): Merge conflict in searx/settings.yml` error)

(searx-py3env) ./manage.sh update_packages

(searx-py3env) cp searx/settings.yml searx/settings.yml_v0170_org

(adjusted searx/settings.yml)

# systemctl start uwsgi.service && systemctl status uwsgi.service
```

The python versions in use are:

```
(searx-py3env) vm-searx:~$ python --version
Python 3.5.3
(searx-py3env) vm-searx:~$ update-alternatives --list python
update-alternatives: error: no alternatives for python

root@vm-searx:~# python --version
Python 2.7.13
root@vm-searx:~# update-alternatives --list python
update-alternatives: error: no alternatives for python
```

**Comment by r4dh4l** [comment]
Btw: I just noticed that the commands in https://searx.github.io/searx/admin/installation-searx.html are missing.

**Comment by r4dh4l** [comment]
I've added a "history of errors" in the starting post.

**Comment by return42** [comment]
> Btw: I just noticed that the commands in https://searx.github.io/searx/admin/installation-searx.html are missing.

Yes / Sorry documentation build is totally broken ATM .. will be fixed by #2211 and #2210

**Comment by virtadpt** [comment]
You might be able to get some use out of the uwsgi Python module; I've never been able to get this particular feature to work, but the Python implementation has been pretty solid for me.

* (in the venv) `pip install uwsgi`
* Contents of `searx.ini` file (used by uwsgi):

```
[uwsgi]
workers = 12
single-interpreter = true
master = true
plugin = python
lazy-apps = true
enable-threads = true
module = searx.webapp
virtualenv = /home/me/searx/env/
pythonpath = /home/me/searx/
chdir = /home/me/searx/searx/
http-socket = 127.0.0.1:8888
disable-logging = true
route-run = fixpathinfo:
```
Shell script I used to start Searx:

```
!/usr/bin/env bash

SEARX=/home/me/searx

# Change to the Searx installation directory.
cd $SEARX

# Initialize the Python virtual environment.
. env/bin/activate

# Start up Searx.
uwsgi --ini searx.ini
```
I hammer on this particular setup pretty hard (a couple of hundred automated search requests per day) and it's been solid.

**Comment by r4dh4l** [comment]
> You might be able to get some use out of the uwsgi Python module

Thx @virtadpt but I would like to get it working with a more standard way at first.

I think I found the problem: The uwsgi template in https://searx.github.io/searx/admin/installation-uwsgi.html for Debian...

```
[uwsgi]

# uWSGI core
# ----------
#
# https://uwsgi-docs.readthedocs.io/en/latest/Options.html#uwsgi-core

# Who will run the code
uid = searx
gid = searx

# set (python) default encoding UTF-8
env = LANG=C.UTF-8
env = LANGUAGE=C.UTF-8
env = LC_ALL=C.UTF-8

# chdir to specified directory before apps loading
chdir = /usr/local/searx/searx-src/searx

# searx configuration (settings.yml)
env = SEARX_SETTINGS_PATH=/etc/searx/settings.yml

# disable logging for privacy
disable-logging = true

# The right granted on the created socket
chmod-socket = 666

# Plugin to use and interpretor config
single-interpreter = true

# enable master process
master = true

# load apps in each worker instead of the master
lazy-apps = true

# load uWSGI plugins
plugin = python3,http

# By default the Python plugin does not initialize the GIL.  This means your
# app-generated threads will not run.  If you need threads, remember to enable
# them with enable-threads.  Running uWSGI in multithreading mode (with the
# threads options) will automatically enable threading support. This *strange*
# default behaviour is for performance reasons.
enable-threads = true


# plugin: python
# --------------
#
# https://uwsgi-docs.readthedocs.io/en/latest/Options.html#plugin-python

# load a WSGI module
module = searx.webapp

# set PYTHONHOME/virtualenv
virtualenv = /usr/local/searx/searx-pyenv

# add directory (or glob) to pythonpath
pythonpath = /usr/local/searx/searx-src


# speak to upstream
# -----------------
#
# Activate the 'http' configuration for filtron or activate the 'socket'
# configuration if you setup your HTTP server to use uWSGI protocol via sockets.

# using IP:
#
# https://uwsgi-docs.readthedocs.io/en/latest/Options.html#plugin-http
# Native HTTP support: https://uwsgi-docs.readthedocs.io/en/latest/HTTP.html

http = 127.0.0.1:8888

# using unix-sockets:
#
# On some distributions you need to create the app folder for the sockets::
#
#   mkdir -p /run/uwsgi/app/searx
#   chown -R searx:searx  /run/uwsgi/app/searx
#
# socket = /run/uwsgi/app/searx/socket
```

...looks very different to mine from Searx 0.15.0:

```

[uwsgi]
# Who will run the code
uid = searx
gid = searx

# disable logging for privacy
disable-logging = true

# Number of workers (usually CPU count)
#workers = 4
workers = 1

# The right granted on the created socket
chmod-socket = 666

# Plugin to use and interpretor config
single-interpreter = true
master = true
plugin = python
lazy-apps = true
enable-threads = true

# Module to import
module = searx.webapp

# Virtualenv and python path
virtualenv = /usr/local/searx/searx-ve/
pythonpath = /usr/local/searx/
chdir = /usr/local/searx/searx/

# filtron
http = 127.0.0.1:8888
```

So what is the path

```
# chdir to specified directory before apps loading
chdir = /usr/local/searx/searx-src/searx
```

in my case? My installation never had a directory `/usr/local/searx/searx-src/`.

**Comment by 0xhtml** [comment]
I would say the paths should be:

```
chdir = /usr/local/searx/searx
virtualenv = /usr/local/searx/searx-py3env
pythonpath = /usr/local/searx
```

But I could be mistaken.
