### ISSUE TITLE
Release v0.10.0

### ISSUE THREAD

**Issue by asciimoo** [searx/searx#659]
It's time to release again!
These are the collected issues need to be done: https://github.com/asciimoo/searx/milestone/2
What else should we include?

**Comment by nerzhul** [comment]
i should test the port revision on FreeBSD to ensure it's compatible with ports tree

**Comment by nerzhul** [comment]
I have upgraded my deps freebsd & searx are synced on same version but i have the following error:

```
/usr/local/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.babel is deprecated, use flask_babel instead.
  .format(x=modname), ExtDeprecationWarning
CRITICAL:searx.plugins:missing attribute "description", cannot load plugin: <module 'searx.plugins.https_rewrite' from '/usr/local/lib/python2.7/site-packages/searx/plugins/https_rewrite.pyc'>
```

**Comment by nerzhul** [comment]
sorry this is due to local installation + package installation on my server, ignore the previous comment. The current version works correctly

**Comment by dalf** [comment]
- [ ] https://github.com/asciimoo/searx/issues/92 ? Google news engine doesn't work.
- [x] https://github.com/asciimoo/searx/issues/571 ? a quick fix is to disable paging support of the google image engine.
- [ ] https://github.com/asciimoo/searx/issues/636 ? The current implementation of the safe search doesn't make sense : safe search is activated for the engines that support it, but other unsafe engines are used too.

**Comment by nerzhul** [comment]
@asciimoo i prepared the port diff to send to FreeBSD, when you tag, tell me, i will test the updated packaged version

**Comment by dalf** [comment]
Another point : does the current requests version support socks proxy (I'm thinking about Tor support) ?
Should 
`requests = 2.10.0`
be replace by
`requests[socks] = 2.10.0` 
(not sure about the syntax, `pip freeze` doesn't show socks dependencie)

Perhaps, Tor support requires more work (enable or not the proxy for each engine for example ?), but this is the first step.

**Comment by ibrokemypie** [comment]
#662 and #651?
